spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yetingfm@2018
    url: jdbc:mysql://193.112.14.58:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 
server:
  #请求加项目名
  context-path: /sell
wechat:
  # 微信授权 id
  mpAppId: wx2c872dd262b57ccc
  mpAppSecret: cf78f255b2e89299a7266c7d7db0c2e6
  openAppId: xxxxxxxxxxxxxxxxxx
  openAppSecret: xxxxxxxxxxxxxxxxxxxxx
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath:  C:/Users/Hasee/Desktop/SpringBoot_Wechat_Sell/src/main/resources/h5.p12
  notifyUrl: http://i5design.viphk.ngrok.org/notify
  templateId:
    orderStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI
    payStatus: kahmCfZjV-2jORZ4yFti9-69smaV3gQ1lFFCDKL_vjI

projectUrl:
  wechatMpAuthorize: http://i5design.viphk.ngrok.org
  wechatOpenAuthorize: http://i5design.viphk.ngrok.org
  sell: http://localhost:8080
logging:
  level:
    com.ldlood.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml





